import re

SECTION_PATTERNS = {
    "must_have": r"(важное требование|обязательное требование)",
    "requirements": r"(требования|мы ожидаем|что ожидаем|что нужно)",
    "responsibilities": r"(обязанности|задачи|что делать|чем предстоит заниматься)",
    "conditions": r"(условия|мы предлагаем|что предлагаем)",
    "tags": r"(стек и теги|стек|технологии|ключевые навыки)",
}

SECTION_HEADERS = {
    "важное требование",
    "обязательное требование",
    "требования",
    "обязанности",
    "задачи",
    "условия",
    "стек и теги",
    "стек",
    "технологии",
    "ключевые навыки",
}

LEVEL_TO_YEARS = {
    "intern": 0.0,
    "стажер": 0.0,
    "junior": 1.0,
    "джуниор": 1.0,
    "middle": 3.0,
    "middle+": 4.0,
    "senior": 5.0,
    "сеньор": 5.0,
    "lead": 7.0,
    "тимлид": 7.0,
}

BULLET_ONLY_RE = re.compile(r"^[•●▪◦·\-–—*]+$")
SPACE_RE = re.compile(r"\s+")
MULTI_NL_RE = re.compile(r"\n{3,}")


TERM_MAP = {
    "golang": "go",
    "питон": "python",
    "джава": "java",
    "яваскрипт": "javascript",
    "js": "javascript",
    "тайпскрипт": "typescript",
    "ts": "typescript",
    "микросервис": "microservices",
    "микросервисный": "microservices",
    "microservice": "microservices",
    "лидерство": "lead",
    "лидер": "lead",
    "тимлид": "lead",
    "тимлида": "lead",
    "тимлидер": "lead",
    "руководитель": "lead",
    "менторинг": "mentoring",
    "наставничество": "mentoring",
    "постгрес": "postgresql",
    "postgres": "postgresql",
    "монго": "mongodb",
    "mongo": "mongodb",
    "эластик": "elasticsearch",
    "elastic": "elasticsearch",
    "кубернетес": "kubernetes",
    "кубернетёс": "kubernetes",
    "кубер": "kubernetes",
    "k8s": "kubernetes",
    "докер": "docker",
    "разработка": "development",
    "бэкенд": "backend",
    "бекенд": "backend",
    "фронтенд": "frontend",
    "фулстек": "fullstack",
    "full-stack": "fullstack",
    "скрам": "scrum",
    "аджайл": "agile",
    "канбан": "kanban",
    "распределённый": "distributed",
    "высоконагруженный": "highload",
    "масштабируемость": "scalability",
    "производительность": "performance",
    "отказоустойчивость": "fault_tolerance",
}

FALLBACK_TECH_TAGS = sorted({
    *TERM_MAP.values(),
    "sql",
    "rest",
    "grpc",
    "docker",
    "kubernetes",
    "helm",
    "grafana",
    "prometheus",
    "victoriametrics",
    "vault",
    "postgresql",
    "mongodb",
    "redis",
    "rabbitmq",
    "kafka",
    "nats",
    "clickhouse",
    "airflow",
    "spark",
    "hadoop",
    "etl",
    "dwh",
    "linux",
    "bash",
    "python",
    "java",
    "go",
    "javascript",
    "typescript",
    ".net",
    "c++",
    "gitlab ci/cd",
    "ci/cd",
    "backend",
    "frontend",
    "fullstack",
}, key=len, reverse=True)