server {
    listen 80;
    server_name localhost;


    location /candidates/upload {
        client_max_body_size 20M;

        include uwsgi_params;
        uwsgi_pass unix:/tmp/socket.sock;
    }

    location / {
        uwsgi_pass unix:/tmp/socket.sock;
        include uwsgi_params;
        uwsgi_read_timeout 600;
        uwsgi_send_timeout 600;
        uwsgi_connect_timeout 75;
    }
}
