server {
    listen 80;
    server_name localhost;

    location / {
        uwsgi_pass unix:/tmp/socket.sock;
        include uwsgi_params;
        uwsgi_read_timeout 600;
        uwsgi_send_timeout 600;
        uwsgi_connect_timeout 75;
    }
}
